repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.100.0
    hooks:
      - id: terraform_fmt
      - id: terraform_validate
        args:
          - '--hook-config=--retry-once-with-cleanup=true'
      - id: terraform_docs
        args:
          - '--hook-config=--add-to-existing-file=true'
        args:
          - '--args=--lockfile=false'
      - id: terraform_tflint
      - id: terraform_trivy
        args:
          - '--args=--tf-exclude-downloaded-modules'
          - '--args=--skip-dirs="**/.terraform"'
          - '--args=--severity MEDIUM,HIGH,CRITICAL'
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: check-merge-conflict
      - id: end-of-file-fixer
  - repo: https://github.com/psf/black
    rev: 25.9.0
    hooks:
      - id: black
        args:
          - '--line-length=88'
  - repo: https://github.com/pycqa/flake8
    rev: 7.3.0
    hooks:
      - id: flake8
        args:
          - '--max-line-length=88'
